# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-28 19:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemes', '0002_auto_20190622_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheme',
            name='completion',
            field=models.IntegerField(default=0, help_text='Enter a percentage as whole number, (e.g. 25 for Partially Complete or 100 for Complete)'),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
